### ISSUE TITLE
[Bug] Console Error

### ISSUE THREAD

**Issue by Emivg** [SimonAsaert/SleepMultiplier#1]
Seems the plugin works fine, but when I fall asleep there is a error in the console that will repeat every second upon I restart my server or disable the plugin in the specified world

`[15:25:09] [Craft Scheduler Thread - 555/WARN]: [SleepMultiplier] Plugin SleepMultiplier v0.1 generated an exception while executing task 87
java.lang.IllegalStateException: TimeSkipEvent may only be triggered synchronously.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:549) ~[patched_1.15.2.jar:git-Paper-84]
	at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.setFullTime(CraftWorld.java:911) ~[patched_1.15.2.jar:git-Paper-84]
	at tld.sima.sleepmultiplier.Main$1.run(Main.java:54) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-84]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-84]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-84]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]`

**Comment by SimonAsaert** [comment]
I must apologise, I haven't pushed the latest build onto GitHub in a while. I think I can make a quick fix for the issue but I haven't had the time recently to properly develop plugins, my degree having taken most my time!
